# Support setting device serial numbers when creating images.
# Note that the '$' is escaped so that environment variable replacement
# happens at "burn" time rather than at firmware creation time. No
# serial numbers are stored in the .fw file. If left blank, the device
# uses the Tegra chip UID that U-Boot passes in the device tree.
uboot_setenv(uboot-env, "nerves_serial_number", "\${NERVES_SERIAL_NUMBER}")
